spring:
  application:
    name: point-service
  config:
    import: nacos:point-service-dev.yml
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
