version: '3.7'

services:
  admin-data-service:
    build:
      context: ./admin-data-service
      dockerfile: Dockerfile
    container_name: admin-data-service
    ports:
      - "9085:9085"
    depends_on:
      - gateway-service
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER-ADDR=nacos:8848
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_GRPC_SERVER-ADDR=nacos:9848

  admin-personnel-service:
    build:
      context: ./admin-personnel-service
      dockerfile: Dockerfile
    container_name: admin-personnel-service
    ports:
      - "9084:9084"
    depends_on:
      - gateway-service
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - NACOS_SERVER_ADDR=nacos:8848
      - SPRING_PROFILES_ACTIVE=prod

  admin-task-service:
    build:
      context: ./admin-task-service
      dockerfile: Dockerfile
    container_name: admin-task-service
    ports:
      - "9083:9083"
    depends_on:
      - gateway-service
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER-ADDR=nacos:8848
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_GRPC_SERVER-ADDR=nacos:9848

  data-screen-service:
    build:
      context: ./data-screen-service
      dockerfile: Dockerfile
    container_name: data-screen-service
    ports:
      - "9086:9086"
    depends_on:
      - gateway-service
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER-ADDR=nacos:8848
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_GRPC_SERVER-ADDR=nacos:9848

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "9998:9998"
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER-ADDR=nacos:8848
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_GRPC_SERVER-ADDR=nacos:9848

  inspector-service:
    build:
      context: ./inspector-service
      dockerfile: Dockerfile
    container_name: inspector-service
    ports:
      - "9082:9082"
    depends_on:
      - gateway-service
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER-ADDR=nacos:8848
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_GRPC_SERVER-ADDR=nacos:9848

  location-service:
    build:
      context: ./location-service
      dockerfile: Dockerfile
    container_name: location-service
    ports:
      - "9087:9087"
    depends_on:
      - gateway-service
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER-ADDR=nacos:8848
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_GRPC_SERVER-ADDR=nacos:9848

  supervisor-service:
    build:
      context: ./supervisor-service
      dockerfile: Dockerfile
    container_name: supervisor-service
    ports:
      - "9081:9081"
    depends_on:
      - gateway-service
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER-ADDR=nacos:8848
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_GRPC_SERVER-ADDR=nacos:9848

networks:
  mynetwork:
