version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: neu1437-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: B430@2023
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - mynetwork

  redis:
    image: redis:5.0.14
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - mynetwork

  nacos:
    hostname: nacos
    image: nacos/nacos-server:2.0.3
    container_name: neu1437-nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    networks:
      - mynetwork
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - TZ=Asia/Shanghai
    volumes:
      - ./nacos-data:/home/nacos/data
    deploy:
      resources:
        limits:
          memory: 1000M

  sentinel:
    image: bladex/sentinel-dashboard:1.8.5
    container_name: sentinel
    ports:
      - "8719:8719"
    networks:
      - mynetwork

  seata:
    image: seataio/seata-server:1.5.2
    container_name: seata
    ports:
      - "8091:8091"
    networks:
      - mynetwork

  elasticsearch:
    image: elasticsearch:7.17.6
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 500M

volumes:
  elasticsearch_data:

networks:
  mynetwork:
