spring:
  application:
    name: gateway-service
  config:
    import: nacos:gateway-service-dev.yml
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml

#server:
#  port: 9998
#
#spring:
#  application:
#    name: gateway-service
#  config:
#    import: optional:nacos:gateway-service-dev.yml
#  redis:
#    host: localhost
#    port: 6379
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#      config:
#        server-addr: localhost:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#        port: 8719
#    gateway:
#      default-filters:
#        - AddRequestHeader=origin,gateway # 添加名为origin的请求头，值为gateway
#      globalcors:
#        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
#        corsConfigurations:
#          '[/**]': # 匹配所有请求
#            allowedOriginPatterns:
#              # - "http://localhost:8080"
#              # - "http://localhost:8081"
#              # - "http://localhost:8112"
#              - "http://*"
#              - "https://*"
#            allowedMethods:
#              - "GET"
#              - "POST"
#              - "PUT"
#              - "DELETE"
#              - "OPTIONS"
#            allowedHeaders: "*"
#            allowCredentials: true
#      discovery:
#        locator:
#          enabled: true #开启注册中心路由 功能
#      routes: # 路由
#        - id: admin-task-service
#          uri: lb://admin-task-service
#          predicates:
#            - Path=/api/admin/task/**
#        - id: admin-data-service
#          uri: lb://admin-data-service
#          predicates:
#            - Path=/api/admin/data/**
#        - id: admin-personnel-service
#          uri: lb://admin-personnel-service
#          predicates:
#            - Path=/api/admin/personnel/**
#        - id: supervisor-service
#          uri: lb://supervisor-service
#          predicates:
#            - Path=/api/supervisor/**
#        - id: inspector-service
#          uri: lb://inspector-service
#          predicates:
#            - Path=/api/inspector/**
#        - id: data-screen-service
#          uri: lb://data-screen-service
#          predicates:
#            - Path=/api/dataScreen/**
#        - id: location-service
#          uri: lb://location-service
#          predicates:
#            - Path=/api/location/**
#
#config:
#  redisTimeout: 60


