server:
  address: 0.0.0.0
  port: 9998

spring:
  application:
    name: gateway-service
  config:
    import: optional:nacos:gateway-service-prod.yml
  redis:
    host: redis
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    sentinel:
      transport:
        dashboard: sentinel-dashboard:8080
        port: 8719
    gateway:
      default-filters:
        - AddRequestHeader=origin,gateway
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://*"
              - "https://*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-task-service
          uri: lb://admin-task-service
          predicates:
            - Path=/api/admin/task/**
        - id: admin-data-service
          uri: lb://admin-data-service
          predicates:
            - Path=/api/admin/data/**
        - id: admin-personnel-service
          uri: lb://admin-personnel-service
          predicates:
            - Path=/api/admin/personnel/**
        - id: supervisor-service
          uri: lb://supervisor-service
          predicates:
            - Path=/api/supervisor/**
        - id: inspector-service
          uri: lb://inspector-service
          predicates:
            - Path=/api/inspector/**
        - id: data-screen-service
          uri: lb://data-screen-service
          predicates:
            - Path=/api/dataScreen/**
        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=/api/location/**

config:
  redisTimeout: 60

#spring:
#  application:
#    name: gateway-service
#  config:
#    import: nacos:gateway-service-prod.yml
#    activate:
#      on-profile: prod
##  profiles:
##    active: dev
#  cloud:
#    nacos:
#      discovery:
#        server-addr: nacos:8848
#      config:
#        server-addr: nacos:8848
#        file-extension: yml