#spring:
#  application:
#    name: inspector-service
#  config:
#    import: nacos:inspector-service-dev.yml
#  profiles:
#    active: dev
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#      config:
#        server-addr: localhost:8848
#        file-extension: yml

server:
  port: 9082
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  application:
    name: inspector-service
  config:
    import: optional:nacos:inspector-service-dev.yml
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-p5gfqnbw.sql.tencentcdb.com:26557/eps
    username: root
    password: B430@2023
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3600000 # 1小时
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    # password: 123456
  elasticsearch:
    host: localhost
    port: 9200
    username: root
    password: 123456
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    time-zone: GMT

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.b430.inspectorservice.controller

seata:
  enabled: true
  application-id: inspector-service
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
  grouplist:
    default: 127.0.0.1:8091
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: DEFAULT_GROUP
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      group: DEFAULT_GROUP
